ProjectManagement.Web/ViewComponents/MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace ProjectManagement.Web.ViewComponents
{
    public class MenuViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View("Menu");
        }
    }
}

ProjectManagement.Web/ViewComponents/ToolbarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ProjectManagement.Application.Services.Interfaces;
using ProjectManagement.Web.PresentationExtensions;

namespace ProjectManagement.Web.ViewComponents
{
    public class ToolbarViewComponent : ViewComponent
    {
        private readonly INotificationService _notificationService;

        public ToolbarViewComponent(INotificationService notificationService)
        {
            _notificationService = notificationService;
        }


        public async Task<IViewComponentResult> InvokeAsync()
        {
            var data = await _notificationService.GetNotifications(User.GetUserId());
            return View("Toolbar", data);
        }
    }

    //public class NotificationsViewComponent : ViewComponent
    //{
    //    private readonly INotificationService _notificationService;

    //    public NotificationsViewComponent(INotificationService notificationService)
    //    {
    //        _notificationService = notificationService;
    //    }
    //    public async Task<IViewComponentResult> InvokeAsync()
    //    {
    //        var data = await _notificationService.GetNotifications(User.GetUserId());
    //        return View("Notifications", data);
    //    }
    //}
}

ProjectManagement.Web/Views/Shared/PageNotFound.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<!--
نویسنده: ساتراس وب
محصولات نام: مترونیک - Bootstrap 5 HTML, VueJS, React, Angular & Laravel Admin داشبورد Theme
خرید: https://1.envato.market/EA4JP
وب سایت: http://www.keenthemes.com
تماس با ما: support@keenthemes.com
دنبال کردن: www.twitter.com/keenthemes
دریبل: www.dribbble.com/keenthemes
Like: www.facebook.com/keenthemes
لاینسس شده: For each use you must have a valid license purchased only from above link in order to legally use the theme for your project.
-->
<html direction="rtl" dir="rtl" style="direction: rtl" >
	<!--begin::Head-->
	<head><base href="../../">
		<title>قالب مدیریت مترونیک</title>
		<meta charset="utf-8" />
		<meta name="description" content="The most advanced پنل ادمین بوت استراپ Theme on Themeforest trusted by 94,000 beginners و professionals. Multi-demo, حالت تیره, RTL support و complete React, Angular, Vue &amp; Laravel versions. Grab your copy now و get life-time updates for free." />
		<meta name="keywords" content="مترونیک, bootstrap, bootstrap 5, Angular, VueJs, React, Laravel, admin themes, web design, figma, web development, free templates, free admin themes, bootstrap theme, bootstrap template, bootstrap dashboard, bootstrap dak mode, bootstrap button, bootstrap datepicker, bootstrap timepicker, fullcalendar, datatables, flaticon" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<meta property="og:locale" content="en_US" />
		<meta property="og:type" content="article" />
		<meta property="og:title" content="قالب مدیریت مترونیک" />
		<meta property="og:url" content="https://keenthemes.com/metronic" />
		<meta property="og:site_name" content="ساتراس وب | مترونیک" />
		<link rel="canonical" href="Https://preview.keenthemes.com/metronic8" />
		<link rel="shortcut icon" href="~/Theme/assets/media/logos/favicon.ico" />
		<!--begin::Fonts-->
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" />
		<!--end::Fonts-->
		<!--begin::Global Stylesheets Bundle(used by all pages)-->
    <link href="~/Theme/assets/plugins/global/plugins.dark.bundle.rtl.css" rel="stylesheet" type="text/css" />
    <link href="~/Theme/assets/css/style.dark.bundle.rtl.css" rel="stylesheet" type="text/css" />
		<!--end::Global Stylesheets Bundle-->
	</head>
	<!--end::Head-->
	<!--begin::Body-->
	<body id="kt_body" class="auth-bg">
		<!--begin::Main-->
		<!--begin::Root-->
		<div class="d-flex flex-column flex-root">
			<!--begin::احراز هویت - 404 Page-->
			<div class="d-flex flex-column flex-center flex-column-fluid p-10">
				<!--begin::Illustration-->
			<img src="~/Theme/assets/media/illustrations/sketchy-1/18.png" alt="" class="mw-100 mb-10 h-lg-450px" />
				<!--end::Illustration-->
				<!--begin::Message-->
				<h1 class="fw-bold mb-10" style="color: #A3A3C7">انگار اینجا چیزی نیست</h1>
				<!--end::Message-->
				<!--begin::Link-->
				<a href="../../demo1/dist/index.html" class="btn btn-primary">برو به صفحه اصلی</a>
				<!--end::Link-->
			</div>
			<!--end::احراز هویت - 404 Page-->
		</div>
		<!--end::Root-->
		<!--end::Main-->
		<!--begin::Javascript-->
	<script>var hostUrl = "~/Theme/assets/";</script>
		<!--begin::Global Javascript Bundle(used by all pages)-->
	<script src="~/Theme/assets/plugins/global/plugins.bundle.js"></script>
	<script src="~/Theme/assets/js/scripts.bundle.js"></script>
		<!--end::Global Javascript Bundle-->
		<!--end::Javascript-->
	</body>
	<!--end::Body-->
</html>

ProjectManagement.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html direction="rtl" dir="rtl" style="direction: rtl">
<head>
    <base href="">
    <title>سامانه پروژه و کارآموزی | @ViewData["Title"]</title>
    <meta charset="utf-8" />
    @*<meta name="description" content="The most advanced پنل ادمین بوت استراپ Theme on Themeforest trusted by 94,000 beginners و professionals. Multi-demo, حالت تیره, RTL support و complete React, Angular, Vue &amp; Laravel versions. Grab your copy now و get life-time updates for free." />*@
    @*<meta name="keywords" content="مترونیک, bootstrap, bootstrap 5, Angular, VueJs, React, Laravel, admin themes, web design, figma, web development, free templates, free admin themes, bootstrap theme, bootstrap template, bootstrap dashboard, bootstrap dak mode, bootstrap button, bootstrap datepicker, bootstrap timepicker, fullcalendar, datatables, flaticon" />*@
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta property="og:locale" content="en_US" />
    <link rel="apple-touch-icon" sizes="180x180" href="~/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/favicon-16x16.png">
    <link rel="manifest" href="~/site.webmanifest">
    @*<meta property="og:type" content="article" />*@
    @*    <meta property="og:title" content="قالب مدیریت مترونیک" />
    <meta property="og:url" content="https://keenthemes.com/metronic" />
    <meta property="og:site_name" content="ساتراس وب | مترونیک" />*@
    <link rel="canonical" href="Https://preview.keenthemes.com/metronic8" />
    <!--begin::Fonts-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" />
    <!--end::Fonts-->
    <!--begin::Global Stylesheets Bundle(used by all pages)-->
    <link href="~/Theme/assets/plugins/global/plugins.dark.bundle.rtl.css" rel="stylesheet" type="text/css" />
    <link href="~/Theme/assets/css/style.dark.bundle.rtl.css" rel="stylesheet" type="text/css" />
    <link href="~/css/waitMe.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/style.css" rel="stylesheet" type="text/css" />
    @await RenderSectionAsync("Css", required: false)
    <!--end::Global Stylesheets Bundle-->
</head>
<body id="kt_body" class="header-fixed header-tablet-and-mobile-fixed toolbar-enabled toolbar-fixed aside-enabled aside-fixed" style="--kt-toolbar-height:55px;--kt-toolbar-height-tablet-and-mobile:55px">

    <!--begin::Main-->
    <!--begin::Root-->
    <div class="d-flex flex-column flex-root">
        <!--begin::Page-->
        <div class="page d-flex flex-row flex-column-fluid">
            <!--begin::کناری-->
            @await Component.InvokeAsync("Menu")

            <!--end::کناری-->
            <!--begin::Wrapper-->
            <div class="wrapper d-flex flex-column flex-row-fluid" id="kt_wrapper">
                <!--begin::Header-->
                <div id="kt_header" style="" class="header align-items-stretch">
                    <!--begin::Container-->
                    <div class="container-fluid d-flex align-items-stretch justify-content-between">
                        <!--begin::کناری mobile toggle-->
                        <div class="d-flex align-items-center d-lg-none ms-n2 me-2" title="مشاهده aside menu">
                            <div class="btn btn-icon btn-active-light-primary w-30px h-30px w-md-40px h-md-40px" id="kt_aside_mobile_toggle">
                                <!--begin::Svg Icon | path: icons/duotune/abstract/abs015.svg-->
                                <span class="svg-icon svg-icon-1">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                        <path d="M21 7H3C2.4 7 2 6.6 2 6V4C2 3.4 2.4 3 3 3H21C21.6 3 22 3.4 22 4V6C22 6.6 21.6 7 21 7Z" fill="currentColor" />
                                        <path opacity="0.3" d="M21 14H3C2.4 14 2 13.6 2 13V11C2 10.4 2.4 10 3 10H21C21.6 10 22 10.4 22 11V13C22 13.6 21.6 14 21 14ZM22 20V18C22 17.4 21.6 17 21 17H3C2.4 17 2 17.4 2 18V20C2 20.6 2.4 21 3 21H21C21.6 21 22 20.6 22 20Z" fill="currentColor" />
                                    </svg>
                                </span>
                                <!--end::Svg Icon-->
                            </div>
                        </div>
                        <!--end::کناری mobile toggle-->
                        <!--begin::Mobile logo-->
                        <div class="d-flex align-items-center flex-grow-1 flex-lg-grow-0">
                            <a asp-action="Index" asp-controller="Home" class="d-lg-none">
                                <img alt="Logo" src="~/images/logo/D.png" style="height: 67px;" class="h-30px" />
                            </a>
                        </div>
                        <!--end::Mobile logo-->
                        <!--begin::Wrapper-->
                        <div class="d-flex align-items-stretch justify-content-between flex-lg-grow-1">
                            <!--begin::Navbar-->
                            <div class="d-flex align-items-stretch" id="kt_header_nav">
                                <!--begin::Menu wrapper-->
                                <div class="header-menu align-items-stretch" data-kt-drawer="true" data-kt-drawer-name="header-menu" data-kt-drawer-activate="{default: true, lg: false}" data-kt-drawer-overlay="true" data-kt-drawer-width="{default:'200px', '300px': '250px'}" data-kt-drawer-direction="end" data-kt-drawer-toggle="#kt_header_menu_mobile_toggle" data-kt-swapper="true" data-kt-swapper-mode="prepend" data-kt-swapper-parent="{default: '#kt_body', lg: '#kt_header_nav'}">
                                    <!--begin::Menu-->
                                    <div class="menu menu-lg-rounded menu-column menu-lg-row menu-state-bg menu-title-gray-700 menu-state-title-primary menu-state-icon-primary menu-state-bullet-primary menu-arrow-gray-400 fw-bold my-5 my-lg-0 align-items-stretch" id="#kt_header_menu" data-kt-menu="true">
                                        <div data-kt-menu-placement="bottom-end" class="menu-item here show menu-lg-down-accordion me-lg-1">
                                            <span class="menu-link py-3" style="cursor: initial; background-color: initial;">
                                                <span class="menu-title" style="font-size: 20px;">سامانه مدیریتی دروس پروژه و کارآموزی</span>
                                                <span class="menu-arrow d-lg-none"></span>
                                            </span>
                                        </div>
                                    </div>
                                    <!--end::Menu-->
                                </div>
                                <!--end::Menu wrapper-->
                            </div>
                            <!--end::Navbar-->
                            <!--begin::Toolbar wrapper-->
                            @await Component.InvokeAsync("Toolbar")
                           @* <script>
                                function done() {
                                    $.ajax({
                                        url: '@Url.Action("ReadAllNotifications", "Home")',
                                        data: {},
                                        success: function (data) {
                                            $("#notif").html("");
                                            $("#notif").html(data);
                                        }
                                    })
                                };

                            </script>*@

                            <!--end::Toolbar wrapper-->
                        </div>
                        <!--end::Wrapper-->
                    </div>
                    <!--end::Container-->
                </div>
                <!--end::Header-->
                <!--begin::Content-->
                <div class="content d-flex flex-column flex-column-fluid" id="kt_content">
                    @RenderBody()
                </div>
                <!--end::Content-->
                <!--begin::Footer-->
                <div class="footer py-4 d-flex flex-lg-column" id="kt_footer">
                    <!--begin::Container-->
                    <div class="container-fluid d-flex flex-column flex-md-row align-items-center justify-content-between">
                        <!--begin::Copyright-->
                        <div class="text-dark order-2 order-md-1">
                            @*								<span class="text-muted fw-bold me-1">2022©</span>
                            <a href="https://keenthemes.com" target="_blank" class="text-gray-800 text-hover-primary">ساتراس وب</a>*@
                            <span class="text-muted fw-bold me-1">1401© | تمام حقوق مادی و معنوی این وب‌سايت متعلق به دانشکده فنی و حرفه ای انقلاب اسلامی است.</span>
                        </div>
                        <!--end::Copyright-->
                        <!--begin::Menu-->
                        <ul class="menu menu-gray-600 menu-hover-primary fw-bold order-1">
                            @*								<li class="menu-item">
                            <a href="https://keenthemes.com" target="_blank" class="menu-link px-2">درباره ی ما</a>
                            </li>
                            <li class="menu-item">
                            <a href="https://rtl-theme.com" target="_blank" class="menu-link px-2">پشتیبانی</a>
                            </li>
                            <li class="menu-item">
                            <a href="https://www.rtl-theme.com/metronic-admin-html-template/" target="_blank" class="menu-link px-2">خرید</a>
                            </li>*@
                            <li class="menu-item">
                                <a href="https://tvct1.tvu.ac.ir" target="_blank" class="menu-link px-2">سایت دانشکده</a>
                            </li>
                            <li class="menu-item">
                                <a href="#" class="menu-link px-2">درباره ما</a>
                            </li>
                        </ul>
                        <!--end::Menu-->
                    </div>
                    <!--end::Container-->
                </div>
                <!--end::Footer-->
            </div>
            <!--end::Wrapper-->
        </div>
        <!--end::Page-->
    </div>
    <!--end::Root-->
    <!--begin::کشوs-->
    <!--begin::فعالیتها drawer-->
    <!--begin::Javascript-->
    <script>var hostUrl = "~/Theme/assets/";</script>
    @await RenderSectionAsync("Scripts", required: false)

    <!--begin::Global Javascript Bundle(used by all pages)-->
    <script src="~/Theme/assets/plugins/global/plugins.bundle.js"></script>
    <script src="~/Theme/assets/js/scripts.bundle.js"></script>
    <!--end::Global Javascript Bundle-->
    <!--begin::Page Vendors Javascript(used by this page)-->
    @*		<script src="~/Theme/assets/plugins/custom/fullcalendar/fullcalendar.bundle.js"></script>
    <script src="~/Theme/assets/plugins/custom/datatables/datatables.bundle.js"></script>*@
    <!--end::Page Vendors Javascript-->
    @*		<!--begin::Page سفارشی Javascript(used by this page)-->

    <!--end::Page custom Javascript-->*@
    <!--end::Javascript-->

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/waitMe.min.js"></script>
    <script src="~/js/custom.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

ProjectManagement.Web/Views/Shared/_NewsSectionPartial.cshtml
@using ProjectManagement.Application.Extensions
@using ProjectManagement.DataLayer.DTOs.Common
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using ProjectManagement.Application.Services.Interfaces
@using ProjectManagement.DataLayer.Entities.Common
@using ProjectManagement.Web.PresentationExtensions
@model List<ProjectManagement.DataLayer.DTOs.Common.NewsDto>
@inject IStudentService StudentService;
@inject ITeacherService TeacherService;
@{
    var studentId = User.GetId();  
    bool hasProject;
    bool hasInternship;
    if (User.IsStudent())
    {
        hasProject = await StudentService.HasCourse(1, studentId);
        hasInternship = await StudentService.HasCourse(2, studentId);
    }
    else
    {
        var teacher = await TeacherService.GetTeacherByUserId(User.GetUserId());
        hasProject = teacher.Project;
        hasInternship = teacher.Internship;
    }
}

<div class="card card-xl-stretch mb-xl-8" style="height: 100%;">
    <div class="card-header align-items-center border-0 mt-4">
        <h3 class="card-title align-items-start flex-column">
            <span class="fw-bolder text-dark">آخرین اطلاعیه ها</span>
            <span class="text-muted mt-1 fw-bold fs-7">متناسب با دروس شما</span>
        </h3>
    </div>
    <!--begin::Body-->
    <div class="card-body pt-3">
        @if (Model.Any())
        {
            var last = Model.Last();
            foreach (var item in Model)
            {
                if (!hasProject && item.Type == InfoType.Project) continue;
                if (!hasInternship && item.Type == InfoType.Internship) continue;

                <div class="d-flex align-items-sm-center mb-7">
                    <div class="d-flex flex-row-fluid flex-wrap align-items-center">
                        <div class="flex-grow-1 me-2">
                            <a href="#" data-bs-toggle="modal" data-bs-target="#kt_modal_new_target-@item.NewsId" class="text-gray-800 fw-bolder text-hover-primary fs-6">@item.Title</a>
                            <span class="text-muted fw-bold d-block pt-1">@item.CreationDate</span>
                        </div>
                        @switch (item.Importance)
                        {
                            case Importance.Information:
                                <span class="badge badge-light-success fs-8 fw-bolder my-2">@item.Importance.GetEnumName()</span>
                                break;
                            case Importance.Instant:
                                <span class="badge badge-light-danger fs-8 fw-bolder my-2">@item.Importance.GetEnumName()</span>
                                break;
                            case Importance.Important:
                                <span class="badge badge-light-warning fs-8 fw-bolder my-2">@item.Importance.GetEnumName()</span>
                                break;
                        }
                    </div>
                </div>
                @if (!item.Equals(last))
                {
                    <div class="separator separator-dashed my-3"></div>
                }

                <div class="modal fade" id="kt_modal_new_target-@item.NewsId" tabindex="-1" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered mw-650px">
                        <div class="modal-content rounded">
                            <div class="modal-header pb-0 border-0 justify-content-end">
                                <div class="btn btn-sm btn-icon btn-active-color-primary" data-bs-dismiss="modal">
                                    <span class="svg-icon svg-icon-1">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                            <rect opacity="0.5" x="6" y="17.3137" width="16" height="2" rx="1" transform="rotate(-45 6 17.3137)" fill="currentColor" />
                                            <rect x="7.41422" y="6" width="16" height="2" rx="1" transform="rotate(45 7.41422 6)" fill="currentColor" />
                                        </svg>
                                    </span>
                                </div>
                            </div>
                            <div class="modal-body scroll-y px-10 px-lg-15 pt-0 pb-15">
                                <!--begin::Card body-->
                                <div class="card-body pt-15" style="text-align: center;">
                                    <div class="d-flex flex-center flex-column mb-5">
                                        <p class="fs-3 text-gray-800 text-hover-primary fw-bolder mb-1" style="cursor: initial">@item.Title</p>
                                        <p class="fs-5 fw-bold text-muted text-hover-primary mb-6" style="cursor: initial">ارسال شده در تاریخ @item.CreationDate توسط @item.TeacherFullName</p>
                                    </div>
                                    <div class="separator separator-dashed my-3"></div>
                                    <div class="pb-5 fs-6">
                                        @Html.Raw(item.Body)
                                    </div>
                                </div>
                                <div class="text-center">
                                    <button type="submit" data-bs-dismiss="modal" class="btn btn-secondary">
                                        <span class="indicator-label">بستن</span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        }
        else
        {
            <partial name="_NoDataAvailablePartial" model='new NoDataAvailable { Title = "اطلاعیه ای موجود نیست", Message = "اطلاعیه ای که برای شما نمایش داده شود موجود نیست"}' />
        }
    </div>
</div>

ProjectManagement.Web/Views/Shared/_NoDataAvailablePartial.cshtml
@model ProjectManagement.DataLayer.DTOs.Common.NoDataAvailable

<div class="notice d-flex bg-light-warning rounded border-warning border border-dashed p-6">
    <span class="svg-icon svg-icon-2tx svg-icon-warning me-4">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
            <rect opacity="0.3" x="2" y="2" width="20" height="20" rx="10" fill="currentColor" />
            <rect x="11" y="14" width="7" height="2" rx="1" transform="rotate(-90 11 14)"
                  fill="currentColor" />
            <rect x="11" y="17" width="2" height="2" rx="1" transform="rotate(-90 11 17)"
                  fill="currentColor" />
        </svg>
    </span>
    <div class="d-flex flex-stack flex-grow-1">
        <div class="fw-bold">
            <h4 class="text-gray-900 fw-bolder">@Model.Title</h4>
            <div class="fs-6 text-gray-700">
                @Model.Message
            </div>
        </div>
    </div>
</div>